version: 0.2
phases:
  pre_build:
    commands:
    - npm install
    - npm fund
  build:
    commands:
    - npm rebuild
    - npm test
artifacts:
  files:
    - src/**/*
    - package.json
